# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Local For Vocal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Local For Vocal
  pod 'razorpay-pod'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'SDWebImage' # Often useful for async image if not already there, but keeping to requests.

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
